# Generated by Django 4.2.3 on 2023-07-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('sale', models.IntegerField(default='', max_length=10)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
