# Generated by Django 4.2.3 on 2023-07-10 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default=datetime.date(2023, 7, 10), upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='sale',
            field=models.IntegerField(max_length=10),
        ),
    ]
